name: Unit and Integration Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        working-directory: ./src/Bacon.Ipsum.API.Client/
        run: dotnet restore
      - name: Build
        working-directory: ./src/Bacon.Ipsum.API.Client/
        run: dotnet build --no-restore
      - name: Unit Tests
        working-directory: ./test/Bacon.Ipsum.API.Client.UnitTests/
        run: dotnet test
      - name: Integration Tests
        working-directory: ./test/Bacon.Ipsum.API.Client.IntegrationTests/
        run: dotnet test
